#!/bin/bash
###############################################################################
# Copyright (c) 2015-2017, Lawrence Livermore National Security, LLC.
# 
# Produced at the Lawrence Livermore National Laboratory
# 
# LLNL-CODE-716457
# 
# All rights reserved.
# 
# This file is part of Alpine. 
# 
# For details, see: http://software.llnl.gov/ascent/.
# 
# Please also read ascent/LICENSE
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, 
#   this list of conditions and the disclaimer below.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the disclaimer (as noted below) in the
#   documentation and/or other materials provided with the distribution.
# 
# * Neither the name of the LLNS/LLNL nor the names of its contributors may
#   be used to endorse or promote products derived from this software without
#   specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE LIVERMORE NATIONAL SECURITY,
# LLC, THE U.S. DEPARTMENT OF ENERGY OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
# DAMAGES  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
###############################################################################
sudo: false

language: cpp
compiler:
  - gcc
env:
  global:
  - COMPILER_CC=gcc-4.9
  - COMPILER_CXX=g++-4.9
  - COMPILER_FC=gfortran-4.9
  matrix:
    # we want to test both static and shared, w/ and w/o docs and vtkm.
    - BUILD_SHARED_LIBS=ON
      ENABLE_VTKM=ON
      ENABLE_DOCS=ON
    - BUILD_SHARED_LIBS=OFF
      ENABLE_VTKM=ON
      ENABLE_DOCS=OFF
    - BUILD_SHARED_LIBS=ON
      ENABLE_VTKM=OFF
      ENABLE_DOCS=OFF
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
       - binutils
       - gcc-4.9
       - g++-4.9
       - gfortran-4.9
cache:
  directories:
    - /home/travis/build/Alpine-DAV/uberenv_libs
install:
  # none
script:
  - which g++
  - g++ --version
  - export CC=${COMPILER_CC}
  - export CXX=${COMPILER_CXX}
  - export FC=${COMPILER_FC}
  - ${CC} --version
  - cd $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  # setup spack spec based on our travis options
  - export SPACK_SPEC="%gcc@4.9+mpich"
  - if [ $ENABLE_VTKM = 'OFF' ]; then export SPACK_SPEC=${SPACK_SPEC}~vtkm; fi
  - if [ $ENABLE_DOCS = 'OFF' ]; then export SPACK_SPEC=${SPACK_SPEC}~doc; fi
  - echo $SPACK_SPEC
  # build deps using uberenv
  - cd ..
  - find uberenv_libs -type d | perl -lne 'print tr:/::, " $_"' | sort -n | cut -d' ' -f2
  - travis_wait 40 python ascent/scripts/uberenv/uberenv.py --spec ${SPACK_SPEC}
  - cd $TRAVIS_BUILD_DIR
  # create out-of-source build dir
  #  - mkdir build-debug
  #  - cd    build-debug
  #  # cmake options
  #  # build type
  #  - CMAKE_OPTS="-DCMAKE_BUILD_TYPE=Debug"
  #  # shared or static libs
  #  - CMAKE_OPTS="${CMAKE_OPTS} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
  #  # install path
  #  - CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_INSTALL_PREFIX=../install-debug"
  #  # make sure cmake is in our path
  #  - export CMAKE_BIN_DIR=`ls -d ${TRAVIS_BUILD_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
  #  - export PATH=${CMAKE_BIN_DIR}:$PATH
  #  - echo $PATH
  #  - which cmake
  #  - cmake --version
  #  - export HOST_CONFIG=`ls ../uberenv_libs/*.cmake`
  #  - cmake ${CMAKE_OPTS} -C ${HOST_CONFIG} ../src
  #  # build, test, and install
  #  - make VERBOSE=1
  #  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  #  - make install
  #  # test our examples that demo using an installed ascent
  #  - export CONDUIT_DIR=`ls -d ${TRAVIS_BUILD_DIR}/uberenv_libs/spack/opt/spack/*/*/conduit*`
  #  - export VTKM_DIR=`ls -d ${TRAVIS_BUILD_DIR}/uberenv_libs/spack/opt/spack/*/*/vtkm*`
  #  - export ASCENT_DIR=${TRAVIS_BUILD_DIR}/install-debug
  #  # using with cmake example
  #  - cd ${TRAVIS_BUILD_DIR}/src/examples/using-with-cmake
  #  - mkdir build
  #  - cd build
  #  - export EXAMPLE_CFG="-DASCENT_DIR=${ASCENT_DIR} -DCONDUIT_DIR=${CONDUIT_DIR}"
  #  - if [ $ENABLE_VTKM = 'ON' ]; then export EXAMPLE_CFG="${EXAMPLE_CFG} -DVTKM_DIR=${VTKM_DIR}"; fi
  #  - echo $EXAMPLE_CFG
  #  - cmake  ${EXAMPLE_CFG} ../
  #  - make VERBOSE=1
  #  - ./example
  #  # using with make example (still needs work for static builds)
  #  #- cd ${TRAVIS_BUILD_DIR}/src/examples/using-with-make
  #  #- make
  #  #- env LD_LIBRARY_PATH=${ASCENT_DIR}/lib/:${CONDUIT_DIR}/lib/ ./example
  #  # test run example apps
  #  - cd ${TRAVIS_BUILD_DIR}
  #  - if [ $ENABLE_VTKM = 'ON' ]; then ./scripts/test-run-examples.sh ; fi
  

#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/uberenv_libs
notifications:
  email:
    recipients:
      - cyrush@llnl.gov
      - larsen30@llnl.gov
    on_success: always
    on_failure: always
