#!/bin/bash
###############################################################################
# Copyright (c) 2015-2017, Lawrence Livermore National Security, LLC.
# 
# Produced at the Lawrence Livermore National Laboratory
# 
# LLNL-CODE-716457
# 
# All rights reserved.
# 
# This file is part of Strawman. 
# 
# For details, see: http://software.llnl.gov/strawman/.
# 
# Please also read strawman/LICENSE
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, 
#   this list of conditions and the disclaimer below.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the disclaimer (as noted below) in the
#   documentation and/or other materials provided with the distribution.
# 
# * Neither the name of the LLNS/LLNL nor the names of its contributors may
#   be used to endorse or promote products derived from this software without
#   specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE LIVERMORE NATIONAL SECURITY,
# LLC, THE U.S. DEPARTMENT OF ENERGY OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
# DAMAGES  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# 
###############################################################################
sudo: false

language: cpp
compiler:
  - gcc
env:
  global:
  - COMPILER_CC=gcc-4.9
  - COMPILER_CXX=g++-4.9
  - COMPILER_FC=gfortran-4.9
  matrix:
    # we want to test both static and shared
    - BUILD_SHARED_LIBS=ON
    - BUILD_SHARED_LIBS=OFF
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
       - binutils
       - gcc-4.9
       - g++-4.9
       - gfortran-4.9
install:
  # none
script:
  - which g++
  - g++ --version
  - export CC=${COMPILER_CC}
  - export CXX=${COMPILER_CXX}
  - export FC=${COMPILER_FC}
  - ${CC} --version
  - cd $TRAVIS_BUILD_DIR
  # build deps using uberenv
  - python scripts/uberenv/uberenv.py --spec %gcc@4.9+mpich
  # create out-of-source build dir
  - mkdir travis-debug-build
  - cd    travis-debug-build
  # cmake options
  # build type
  - CMAKE_OPTS="-DCMAKE_BUILD_TYPE=Debug"
  # shared or static libs
  - CMAKE_OPTS="${CMAKE_OPTS} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
  # install path
  - CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_INSTALL_PREFIX=../travis-debug-install"
  # make sure cmake is in our path
  - export CMAKE_BIN_DIR=`ls -d ${TRAVIS_BUILD_DIR}/uberenv_libs/spack/opt/spack/*/*/cmake*/bin`
  - export PATH=${CMAKE_BIN_DIR}:$PATH
  - echo $PATH
  - which cmake
  - cmake --version
  - export HOST_CONFIG=`ls ../uberenv_libs/*.cmake`
  - cmake ${CMAKE_OPTS} -C ${HOST_CONFIG} ../src
  # build, test, and install
  - make VERBOSE=1
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - make install
  # test our examples that demo using an installed strawman
  - export CONDUIT_DIR=`ls -d ${TRAVIS_BUILD_DIR}/uberenv_libs/spack/opt/spack/*/*/conduit*`
  - export VTKM_DIR=`ls -d ${TRAVIS_BUILD_DIR}/uberenv_libs/spack/opt/spack/*/*/vtkm*`
  - export STRAWMAN_DIR=${TRAVIS_BUILD_DIR}/travis-debug-install
  # using with cmake example
  - cd ${TRAVIS_BUILD_DIR}/src/examples/using-with-cmake
  - mkdir build
  - cd build
  - cmake -DSTRAWMAN_DIR=${STRAWMAN_DIR} -DCONDUIT_DIR=${CONDUIT_DIR} -DVTKM_DIR=${VTKM_DIR} ../
  - make VERBOSE=1
  - ./example
  - cat /tmp/travis/spack-stage/spack-stage-fONW9j/cmake-3.4.0/spack-build.out 
  # using with make example (still needs work for static builds)
  #- cd ${TRAVIS_BUILD_DIR}/src/examples/using-with-make
  #- make
  #- env LD_LIBRARY_PATH=${STRAWMAN_DIR}/lib/:${CONDUIT_DIR}/lib/ ./example

#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/uberenv_libs
notifications:
  email:
    recipients:
      - cyrush@llnl.gov
      - larsen30@llnl.gov
    on_success: always
    on_failure: always
