-
  action: "add_scenes"
  probing:
    factor: 0.1
    node_split: 0.8
    batch_count: 2
    insitu_type: "hybrid"
  scenes:
    s1:
      plots:
        p1:
          type: "volume"
          field: "energy"
          min_value: 0.1
          max_value: 15.0
          color_table: 
            name: "rainbow desaturated"
            control_points: 
              - 
                type: "alpha"
                position: 0.0
                alpha: 0.0
              - 
                type: "alpha"
                position: 1.0
                alpha: 1.0
      renders:
        r1:
          type: "cinema"
          phi: 20
          theta: 20
          camera:
            zoom: 0.3
          db_name: "clover_db"
