packages:
  all:
    variants: +openmp
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mvapich2]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
  python:
    variants: ~dbm
  py-numpy:
    variants: ~blas~lapack
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
# ORNL blueos CUDA
  cuda:
    buildable: false
    externals:
    - prefix: /sw/summit/cuda/10.1.243
      spec: cuda@10.1.243
# ORNL blueos mpi
# note, we need to fake this as an existing mpi package
# so even though this is spectrum mpi, we call it mvapich2
  mvapich2:
    buildable: false
    externals:
    - prefix: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-5/spectrum-mpi-10.3.1.2-20200121-p6nrnt6vtvkn356wqg6f74n6jspnpjd2/
      spec: mvapich2@2.2%xl
    - prefix: /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-6.4.0/spectrum-mpi-10.3.1.2-20200121-awz2q5brde7wgdqqw4ugalrkukeub4eb/
      spec: mvapich2@2.2%gcc
